# Generated by Django 5.2.14 on 2026-05-22 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recommendation',
            old_name='destination',
            new_name='designation',
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='description',
            field=models.TextField(help_text='Recommendation Description'),
        ),
    ]
